language: c

dist: trusty

services:
  - postgresql

addons:
  postgresql: "9.5"

install:
  - cd ..
  - mkdir cortoproject
  - mv postgresql cortoproject/postgresql
  - cd cortoproject
  - git clone https://github.com/cortoproject/corto.git
  - git clone https://github.com/cortoproject/c-binding.git
  - git clone https://github.com/cortoproject/json.git
  - git clone https://github.com/cortoproject/xml.git
  - git clone https://github.com/cortoproject/corto-language.git
  - git clone https://github.com/cortoproject/io.git
  - git clone https://github.com/cortoproject/test.git
  - |+
    echo 'COMPONENTS = %w(corto c-binding json xml corto-language io test postgresql)
    require "#{ENV["CORTO_BUILD"]}/forward"' > rakefile
  - source corto/configure
  - rake

before_script:
  - function hashes() { for g in `find . -name .git` ; do d=$(basename $(dirname $g)); h=$(git --git-dir $g rev-parse HEAD) ; echo -e "$d\t$h"; done } ; hashes | column -t | sort
  - psql -c 'create database postgresql_test;' -U postgres
  - psql --version
  - cd postgresql

script:
  - rake test
